### ISSUE TITLE
Sign Windows binaries

### ISSUE THREAD

**Issue by strogonoff** [ituob/itu-ob-editor#45]
Microsoft lists the providers that issue code signing certificates here:

https://docs.microsoft.com/en-gb/windows-hardware/drivers/dashboard/get-a-code-signing-certificate?redirectedfrom=MSDN#extended-validation-code-signing-certificates

I assume they are all paid. I checked and DigiCert apparently costs US $74.

@ronaldtse, to you:

* Do you already work with any of the companies listed by above link? That could influence the choice of certificate issuer

* This is not a requirement right now, but may be when we start distributing the app to end-users. Whether data entry volunteers are considered end-users is an open question.

**Comment by ronaldtse** [comment]
@strogonoff yes we work with DigiCert; we also wrote a Ruby gem for their API which is kind of official :wink:

Let me get back to you today on this...

**Comment by strogonoff** [comment]
Wow, neat! According to MS docs, the certificates are somewhat generic (unlike with Apple, which uses a more opaque mechanism), so I suppose the gem might work.

If obtaining a certificate is a quick process, we can wait for now and do it right before we bring the app to more users. Might make sense since it’s probably going to cost some money too. However, if there’s some sort of approval process, then we should probably apply a bit in advance.

**Comment by ronaldtse** [comment]
This is all done. Closing.
