### ISSUE TITLE
On Windows, the app does not quit when window is closed

### ISSUE THREAD

**Issue by strogonoff** [ituob/itu-ob-editor#57]

**Comment by strogonoff** [comment]
This seems to be related to a situation where a promise is being processed (e.g. repo data fetched) when user closes all windows, similar thing seems to happen during relaunch sequence e.g. when app data is cleared during troubleshooting.

**Comment by strogonoff** [comment]
Reproduction scenario:

* Launch app
* Reset repository URL, which would relaunch the app and trigger fresh repository pull
* After the app started again, close main window while buttons are still disabled (meaning repository is being pulled)
* Processes will hang in Task Manager :(

**Comment by ronaldtse** [comment]
Related to this? https://stackoverflow.com/questions/52105917/electron-windows-app-close-not-ending-threads

**Comment by strogonoff** [comment]
many people reported a similar issue, but generally like in this case it's caused by mistakes our app already isn't making

**Comment by ronaldtse** [comment]
Tested, not occurring anymore.
