### ISSUE TITLE
Error building on GHA (GH_TOKEN related)

### ISSUE THREAD

**Issue by strogonoff** [ituob/itu-ob-editor#72]
Error building ITU OB Editor on GHA, about GH_TOKEN. I believe we should add it in repo secrets[0]? I added mine, but it doesn’t work. Feel free to remove it.

[0] https://github.com/electron-userland/electron-builder/issues/1693#issuecomment-380408619

**Comment by strogonoff** [comment]
I suppose GH_TOKEN I added would not work because I am not the owner of the repository, so perhaps @ronaldtse you could add the appropriate GH_TOKEN. I removed the token I added trying to troubleshoot it.

(It’s not related to signing, but to publishing built release. I will reinstate signing once we have build working otherwise on GHA.)

**Comment by ronaldtse** [comment]
Fixed!
